#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

# This pipeline runs the five analysis experiments:
# 1. head/middle/tail learning curves across checkpoint steps
# 2. gradient-alignment training dynamics
# 3. hidden-state SVD/PCA diagnostics
# 4. feature separability probes
# 5. LM head / embedding frequency-bias diagnostics

RUN_PREFIX="${RUN_PREFIX:-frequency-width-dense}"
HIDDEN_SIZES="${HIDDEN_SIZES:-64 96}"
CONDITIONS="${CONDITIONS:-uniform zipf}"

TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-1000}"
SAVE_INTERVAL="${SAVE_INTERVAL:-50}"
SEQ_LEN="${SEQ_LEN:-128}"
LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE:-16}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-16}"
LR="${LR:-1e-3}"
WARMUP_STEPS="${WARMUP_STEPS:-100}"
TRAINING_SEED="${TRAINING_SEED:-20260605}"

SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES:-200000}"
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE:-4}"
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS:-2}"
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT:-256}"
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER:-64}"
SYNTHETIC_SEED="${SYNTHETIC_SEED:-0}"
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA:-1.3}"
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS:-true}"

ANALYSIS_MODES="${ANALYSIS_MODES:-learning_curve,gradients,svd,probe,lm_bias}"
ANALYSIS_CHECKPOINT_STEPS="${ANALYSIS_CHECKPOINT_STEPS:-all}"
ANALYSIS_NUM_SAMPLES="${ANALYSIS_NUM_SAMPLES:-512}"
ANALYSIS_BATCH_SIZE="${ANALYSIS_BATCH_SIZE:-16}"
ANALYSIS_GRADIENT_SAMPLES="${ANALYSIS_GRADIENT_SAMPLES:-128}"
ANALYSIS_GRADIENT_BATCH_SIZE="${ANALYSIS_GRADIENT_BATCH_SIZE:-16}"
ANALYSIS_SVD_SAMPLES="${ANALYSIS_SVD_SAMPLES:-256}"
ANALYSIS_OUTPUT_PATH="${ANALYSIS_OUTPUT_PATH:-../experiments/${RUN_PREFIX}-five-analysis.json}"

echo "========== frequency-width five-analysis pipeline =========="
echo "run_prefix=${RUN_PREFIX}"
echo "hidden_sizes=${HIDDEN_SIZES}"
echo "conditions=${CONDITIONS}"
echo "train_steps=${TOTAL_TRAINING_STEPS}, save_interval=${SAVE_INTERVAL}"
echo "analysis_modes=${ANALYSIS_MODES}"
echo "analysis_output=${ANALYSIS_OUTPUT_PATH}"
echo "==========================================================="

echo "[$(date)] Step 1/2: train dense checkpoints"
RUN_PREFIX="${RUN_PREFIX}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
CONDITIONS="${CONDITIONS}" \
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS}" \
SAVE_INTERVAL="${SAVE_INTERVAL}" \
SEQ_LEN="${SEQ_LEN}" \
LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE}" \
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}" \
LR="${LR}" \
WARMUP_STEPS="${WARMUP_STEPS}" \
TRAINING_SEED="${TRAINING_SEED}" \
SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA}" \
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS}" \
./run_frequency_width_dense_checkpoints.sh

echo "[$(date)] Step 2/2: run five analysis modes"
RUN_PREFIX="${RUN_PREFIX}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
CONDITIONS="${CONDITIONS}" \
CHECKPOINT_STEPS="${ANALYSIS_CHECKPOINT_STEPS}" \
MODES="${ANALYSIS_MODES}" \
OUTPUT_PATH="${ANALYSIS_OUTPUT_PATH}" \
SEQ_LEN="${SEQ_LEN}" \
NUM_SAMPLES="${ANALYSIS_NUM_SAMPLES}" \
BATCH_SIZE="${ANALYSIS_BATCH_SIZE}" \
GRADIENT_SAMPLES="${ANALYSIS_GRADIENT_SAMPLES}" \
GRADIENT_BATCH_SIZE="${ANALYSIS_GRADIENT_BATCH_SIZE}" \
SVD_SAMPLES="${ANALYSIS_SVD_SAMPLES}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA}" \
./run_frequency_width_all_analysis.sh

echo "[$(date)] done. analysis output: ${ANALYSIS_OUTPUT_PATH}"
