#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

# This pipeline runs the intervention / solution-side experiments:
# 1. Zipf + inverse-frequency loss reweight
# 2. Zipf checkpoint -> uniform fine-tune
# 3. Fixed total training tokens, varying Zipf skew
#
# It intentionally only calls existing launch scripts and does not modify shared
# training/analysis code, so it is safe to create while analysis jobs are running.

HIDDEN_SIZES="${HIDDEN_SIZES:-64 96}"

TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-1000}"
SAVE_INTERVAL="${SAVE_INTERVAL:-100}"
SEQ_LEN="${SEQ_LEN:-128}"
LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE:-16}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-16}"
LR="${LR:-1e-3}"
WARMUP_STEPS="${WARMUP_STEPS:-100}"
TRAINING_SEED="${TRAINING_SEED:-20260605}"

SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES:-200000}"
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE:-4}"
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS:-2}"
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT:-256}"
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER:-64}"
SYNTHETIC_SEED="${SYNTHETIC_SEED:-0}"
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA:-1.3}"
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS:-true}"

REWEIGHT_RUN_PREFIX="${REWEIGHT_RUN_PREFIX:-frequency-width-reweight}"
REWEIGHT_TYPE="${REWEIGHT_TYPE:-inverse_sqrt}"
REWEIGHT_MAX_WEIGHT="${REWEIGHT_MAX_WEIGHT:-10.0}"

FINETUNE_SOURCE_RUN_PREFIX="${FINETUNE_SOURCE_RUN_PREFIX:-frequency-width-dense}"
FINETUNE_SOURCE_STEP="${FINETUNE_SOURCE_STEP:-1000}"
FINETUNE_RUN_PREFIX="${FINETUNE_RUN_PREFIX:-frequency-width-zipf-to-uniform}"
FINETUNE_TOTAL_TRAINING_STEPS="${FINETUNE_TOTAL_TRAINING_STEPS:-300}"
FINETUNE_SAVE_INTERVAL="${FINETUNE_SAVE_INTERVAL:-50}"
FINETUNE_LR="${FINETUNE_LR:-5e-4}"
FINETUNE_WARMUP_STEPS="${FINETUNE_WARMUP_STEPS:-30}"
FINETUNE_TRAINING_SEED="${FINETUNE_TRAINING_SEED:-20260606}"

SKEW_RUN_PREFIX="${SKEW_RUN_PREFIX:-frequency-width-skew}"
ZIPF_ALPHAS="${ZIPF_ALPHAS:-0.7 1.0 1.3 1.6}"
SKEW_CHECKPOINT_STEP="${SKEW_CHECKPOINT_STEP:-${TOTAL_TRAINING_STEPS}}"

ANALYSIS_CHECKPOINT_STEPS="${ANALYSIS_CHECKPOINT_STEPS:-${TOTAL_TRAINING_STEPS}}"
ANALYSIS_MODES="${ANALYSIS_MODES:-learning_curve,gradients,svd,probe,lm_bias}"
ANALYSIS_NUM_SAMPLES="${ANALYSIS_NUM_SAMPLES:-512}"
ANALYSIS_BATCH_SIZE="${ANALYSIS_BATCH_SIZE:-16}"
ANALYSIS_GRADIENT_SAMPLES="${ANALYSIS_GRADIENT_SAMPLES:-128}"
ANALYSIS_GRADIENT_BATCH_SIZE="${ANALYSIS_GRADIENT_BATCH_SIZE:-16}"
ANALYSIS_SVD_SAMPLES="${ANALYSIS_SVD_SAMPLES:-256}"

echo "========== frequency-width solution pipeline =========="
echo "hidden_sizes=${HIDDEN_SIZES}"
echo "train_steps=${TOTAL_TRAINING_STEPS}, save_interval=${SAVE_INTERVAL}"
echo "reweight=${REWEIGHT_TYPE}, max_weight=${REWEIGHT_MAX_WEIGHT}"
echo "finetune_source=${FINETUNE_SOURCE_RUN_PREFIX}-zipf-h*/${FINETUNE_SOURCE_STEP}.pth"
echo "zipf_alphas=${ZIPF_ALPHAS}"
echo "======================================================="

echo "[$(date)] Step 1/6: train Zipf reweight intervention"
RUN_PREFIX="${REWEIGHT_RUN_PREFIX}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
FREQUENCY_LOSS_WEIGHTING="${REWEIGHT_TYPE}" \
FREQUENCY_LOSS_MAX_WEIGHT="${REWEIGHT_MAX_WEIGHT}" \
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS}" \
SAVE_INTERVAL="${SAVE_INTERVAL}" \
SEQ_LEN="${SEQ_LEN}" \
LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE}" \
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}" \
LR="${LR}" \
WARMUP_STEPS="${WARMUP_STEPS}" \
TRAINING_SEED="${TRAINING_SEED}" \
SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA}" \
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS}" \
./run_frequency_width_reweight.sh

echo "[$(date)] Step 2/6: analyze Zipf reweight intervention"
RUN_PREFIX="${REWEIGHT_RUN_PREFIX}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
FREQUENCY_LOSS_WEIGHTING="${REWEIGHT_TYPE}" \
CHECKPOINT_STEPS="${ANALYSIS_CHECKPOINT_STEPS}" \
MODES="${ANALYSIS_MODES}" \
SEQ_LEN="${SEQ_LEN}" \
NUM_SAMPLES="${ANALYSIS_NUM_SAMPLES}" \
BATCH_SIZE="${ANALYSIS_BATCH_SIZE}" \
GRADIENT_SAMPLES="${ANALYSIS_GRADIENT_SAMPLES}" \
GRADIENT_BATCH_SIZE="${ANALYSIS_GRADIENT_BATCH_SIZE}" \
SVD_SAMPLES="${ANALYSIS_SVD_SAMPLES}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA}" \
./run_frequency_width_reweight_analysis.sh

echo "[$(date)] Step 3/6: fine-tune Zipf checkpoints on uniform data"
SOURCE_RUN_PREFIX="${FINETUNE_SOURCE_RUN_PREFIX}" \
RUN_PREFIX="${FINETUNE_RUN_PREFIX}" \
SOURCE_STEP="${FINETUNE_SOURCE_STEP}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
TOTAL_TRAINING_STEPS="${FINETUNE_TOTAL_TRAINING_STEPS}" \
SAVE_INTERVAL="${FINETUNE_SAVE_INTERVAL}" \
SEQ_LEN="${SEQ_LEN}" \
LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE}" \
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}" \
LR="${FINETUNE_LR}" \
WARMUP_STEPS="${FINETUNE_WARMUP_STEPS}" \
TRAINING_SEED="${FINETUNE_TRAINING_SEED}" \
SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA}" \
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS}" \
./run_frequency_width_uniform_finetune.sh

echo "[$(date)] Step 4/6: analyze uniform fine-tune recovery"
RUN_PREFIX="${FINETUNE_RUN_PREFIX}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
CHECKPOINT_STEPS="all" \
MODES="${ANALYSIS_MODES}" \
SEQ_LEN="${SEQ_LEN}" \
NUM_SAMPLES="${ANALYSIS_NUM_SAMPLES}" \
BATCH_SIZE="${ANALYSIS_BATCH_SIZE}" \
GRADIENT_SAMPLES="${ANALYSIS_GRADIENT_SAMPLES}" \
GRADIENT_BATCH_SIZE="${ANALYSIS_GRADIENT_BATCH_SIZE}" \
SVD_SAMPLES="${ANALYSIS_SVD_SAMPLES}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA}" \
./run_frequency_width_uniform_finetune_analysis.sh

echo "[$(date)] Step 5/6: train fixed-token skew sweep"
RUN_PREFIX="${SKEW_RUN_PREFIX}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
ZIPF_ALPHAS="${ZIPF_ALPHAS}" \
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS}" \
SAVE_INTERVAL="${TOTAL_TRAINING_STEPS}" \
SEQ_LEN="${SEQ_LEN}" \
LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE}" \
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}" \
LR="${LR}" \
WARMUP_STEPS="${WARMUP_STEPS}" \
TRAINING_SEED="${TRAINING_SEED}" \
SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS}" \
./run_frequency_width_skew_sweep.sh

echo "[$(date)] Step 6/6: evaluate skew sweep"
RUN_PREFIX="${SKEW_RUN_PREFIX}" \
HIDDEN_SIZES="${HIDDEN_SIZES}" \
ZIPF_ALPHAS="${ZIPF_ALPHAS}" \
CHECKPOINT_STEP="${SKEW_CHECKPOINT_STEP}" \
SEQ_LEN="${SEQ_LEN}" \
EVAL_NUM_SAMPLES="${ANALYSIS_NUM_SAMPLES}" \
EVAL_BATCH_SIZE="${ANALYSIS_BATCH_SIZE}" \
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS}" \
./run_frequency_width_skew_eval.sh

echo "[$(date)] solution pipeline done"
