#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

mkdir -p ../logs ../checkpoints

# Round6 controlled reused-token dataset.
SEQ_LEN="${SEQ_LEN:-128}"
SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES:-200000}"
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE:-4}"
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS:-2}"
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT:-512}"
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER:-512}"
SYNTHETIC_SEED="${SYNTHETIC_SEED:-0}"

CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE:-0.1}"
CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE:-4}"
CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION:-zipf}" # uniform/zipf
CONTROLLED_SAME_INPUT_DIFF_OUTPUT_ZIPF_ALPHA="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_ZIPF_ALPHA:-1.0}"
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE:-0.1}"
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE:-4}"
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION:-zipf}" # uniform/zipf
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_ZIPF_ALPHA="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_ZIPF_ALPHA:-1.0}"
CONTROLLED_TOP_SAMPLING_DISTRIBUTION="${CONTROLLED_TOP_SAMPLING_DISTRIBUTION:-uniform}" # uniform/zipf
CONTROLLED_TOP_SAMPLING_ZIPF_ALPHA="${CONTROLLED_TOP_SAMPLING_ZIPF_ALPHA:-1.0}"

# Small model setting.
DEBUG_VOCAB_SIZE="${DEBUG_VOCAB_SIZE:-513}"
DEBUG_HIDDEN_SIZE="${DEBUG_HIDDEN_SIZE:-64}"
DEBUG_INTERMEDIATE_SIZE="${DEBUG_INTERMEDIATE_SIZE:-128}"
DEBUG_NUM_HIDDEN_LAYERS="${DEBUG_NUM_HIDDEN_LAYERS:-2}"
DEBUG_NUM_ATTENTION_HEADS="${DEBUG_NUM_ATTENTION_HEADS:-4}"
DEBUG_NUM_KEY_VALUE_HEADS="${DEBUG_NUM_KEY_VALUE_HEADS:-2}"
DEBUG_HEAD_DIM="${DEBUG_HEAD_DIM:-16}"
DEBUG_MAX_POSITION_EMBEDDINGS="${DEBUG_MAX_POSITION_EMBEDDINGS:-256}"

# Training setting.
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-2000}"
SAVE_INTERVAL="${SAVE_INTERVAL:-2000}"
LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE:-16}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-16}"
LR="${LR:-1e-3}"
WARMUP_STEPS="${WARMUP_STEPS:-100}"
TRAINING_SEED="${TRAINING_SEED:-20260525}"
RUN_PREFIX="${RUN_PREFIX:-round6-controlled}"

run_case() {
  local suffix="$1"
  local use_moe="$2"
  local router_pos="${3:-hidden}"
  local router_shape="${4:-full}"
  local expert_pos="${5:-attention_output_residual}"
  local expert_shape="${6:-full}"

  local run_name="${RUN_PREFIX}-${suffix}"
  local ckpt_path="../checkpoints/${run_name}/${TOTAL_TRAINING_STEPS}.pth"
  local log_path="../logs/${run_name}.train.log"

  if [ -f "${ckpt_path}" ]; then
    echo "[$(date)] skip ${run_name}: found ${ckpt_path}"
    return 0
  fi

  echo "[$(date)] start ${run_name}"
  echo "  use_moe=${use_moe}, router=${router_pos}/${router_shape}, expert=${expert_pos}/${expert_shape}"

  env \
    RUN_NAME="${run_name}" \
    DATASET_TYPE="controlled_reused_token" \
    TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS}" \
    SAVE_INTERVAL="${SAVE_INTERVAL}" \
    LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE}" \
    GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}" \
    SEQ_LEN="${SEQ_LEN}" \
    SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES}" \
    SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE}" \
    SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS}" \
    SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT}" \
    SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER}" \
    SYNTHETIC_SEED="${SYNTHETIC_SEED}" \
    CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE}" \
    CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE}" \
    CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION}" \
    CONTROLLED_SAME_INPUT_DIFF_OUTPUT_ZIPF_ALPHA="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_ZIPF_ALPHA}" \
    CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE}" \
    CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE}" \
    CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION}" \
    CONTROLLED_DIFF_INPUT_SAME_OUTPUT_ZIPF_ALPHA="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_ZIPF_ALPHA}" \
    CONTROLLED_TOP_SAMPLING_DISTRIBUTION="${CONTROLLED_TOP_SAMPLING_DISTRIBUTION}" \
    CONTROLLED_TOP_SAMPLING_ZIPF_ALPHA="${CONTROLLED_TOP_SAMPLING_ZIPF_ALPHA}" \
    DEBUG_VOCAB_SIZE="${DEBUG_VOCAB_SIZE}" \
    DEBUG_HIDDEN_SIZE="${DEBUG_HIDDEN_SIZE}" \
    DEBUG_INTERMEDIATE_SIZE="${DEBUG_INTERMEDIATE_SIZE}" \
    DEBUG_NUM_HIDDEN_LAYERS="${DEBUG_NUM_HIDDEN_LAYERS}" \
    DEBUG_NUM_ATTENTION_HEADS="${DEBUG_NUM_ATTENTION_HEADS}" \
    DEBUG_NUM_KEY_VALUE_HEADS="${DEBUG_NUM_KEY_VALUE_HEADS}" \
    DEBUG_HEAD_DIM="${DEBUG_HEAD_DIM}" \
    DEBUG_MAX_POSITION_EMBEDDINGS="${DEBUG_MAX_POSITION_EMBEDDINGS}" \
    CKPT_DIR="../checkpoints/${run_name}" \
    USE_MOE="${use_moe}" \
    MOE_NUM_UNIQUE_EXPERTS="${MOE_NUM_UNIQUE_EXPERTS:-4}" \
    MOE_NUM_EXPERTS_PER_TOK="${MOE_NUM_EXPERTS_PER_TOK:-1}" \
    MOE_INTERMEDIATE_SIZE="${MOE_INTERMEDIATE_SIZE:-128}" \
    MOE_USE_COMMON_EXPERT="${MOE_USE_COMMON_EXPERT:-false}" \
    MOE_ROUTER_TYPE="${MOE_ROUTER_TYPE:-linear}" \
    MOE_ROUTER_INPUT="hidden" \
    MOE_ROUTER_INPUT_POS="${router_pos}" \
    MOE_ROUTER_INPUT_SHAPE="${router_shape}" \
    MOE_EXPERT_INPUT_POS="${expert_pos}" \
    MOE_EXPERT_INPUT_SHAPE="${expert_shape}" \
    LR="${LR}" \
    WARMUP_STEPS="${WARMUP_STEPS}" \
    TRAINING_SEED="${TRAINING_SEED}" \
    bash run_inverse_kv_local_experiment.sh > "${log_path}" 2>&1

  echo "[$(date)] done ${run_name}, log=${log_path}"
}

echo "Round6 controlled reused-token dense/MoE experiments start: $(date)"
echo "data: slot=${SYNTHETIC_BLOCK_SIZE}, layers=${SYNTHETIC_NUM_HIERARCHY_LAYERS}, units=${SYNTHETIC_NUM_UNITS_PER_LAYER}, content=${SYNTHETIC_CONTENT_TOKEN_COUNT}"
echo "same-input-diff-output: rate=${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE}, size=${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE}, dist=${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION}"
echo "diff-input-same-output: rate=${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE}, size=${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE}, dist=${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION}"

run_case "dense-h64" "false"
run_case "moe-hidden-full" "true" "hidden" "full" "attention_output_residual" "full"

echo "Round6 controlled reused-token dense/MoE experiments done: $(date)"
