#!/usr/bin/env bash
set -e

cd "$(dirname "$0")"

LOCAL_BATCH_SIZE="${LOCAL_BATCH_SIZE:-2}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-2}"
SAVE_INTERVAL="${SAVE_INTERVAL:-1000}"
SEQ_LEN="${SEQ_LEN:-64}"
DATA_SHUFFLE="${DATA_SHUFFLE:-true}"  # true/false
USE_BF16="${USE_BF16:-false}"  # true/false

OPTIMIZER="${OPTIMIZER:-AdamW}"  # AdamW/sgd
LR="${LR:-1e-4}"
WARMUP_STEPS="${WARMUP_STEPS:-200}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-1000}"
TRAINING_SEED="${TRAINING_SEED:--1}"

NUM_WORKERS="${NUM_WORKERS:-0}"
CONFIG_DIR="${CONFIG_DIR:-../Qwen3-0.6B}"
DATA_DIR="${DATA_DIR:-.}"
DATASET_TYPE="${DATASET_TYPE:-hierarchical_pattern}"  # jsonl/pruned/synthetic_indexed/hierarchical_pattern

SYNTHETIC_NUM_SAMPLES="${SYNTHETIC_NUM_SAMPLES:-128}"
SYNTHETIC_BLOCK_SIZE="${SYNTHETIC_BLOCK_SIZE:-4}"
SYNTHETIC_NUM_HIERARCHY_LAYERS="${SYNTHETIC_NUM_HIERARCHY_LAYERS:-2}"
SYNTHETIC_CONTENT_TOKEN_COUNT="${SYNTHETIC_CONTENT_TOKEN_COUNT:-128}"
SYNTHETIC_NUM_UNITS_PER_LAYER="${SYNTHETIC_NUM_UNITS_PER_LAYER:-32}"
SYNTHETIC_SEED="${SYNTHETIC_SEED:-0}"
SYNTHETIC_PAD_TOKEN_ID="${SYNTHETIC_PAD_TOKEN_ID:-0}"
SYNTHETIC_MIN_TOKEN_ID="${SYNTHETIC_MIN_TOKEN_ID:-1}"
SYNTHETIC_SAMPLING_DISTRIBUTION="${SYNTHETIC_SAMPLING_DISTRIBUTION:-uniform}"  # uniform/zipf
SYNTHETIC_ZIPF_ALPHA="${SYNTHETIC_ZIPF_ALPHA:-1.0}"
SYNTHETIC_ZIPF_SHUFFLE_RANKS="${SYNTHETIC_ZIPF_SHUFFLE_RANKS:-true}"  # true/false
CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE:-0.3}"
CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE:-4}"
CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION:-zipf}"  # uniform/zipf
CONTROLLED_SAME_INPUT_DIFF_OUTPUT_ZIPF_ALPHA="${CONTROLLED_SAME_INPUT_DIFF_OUTPUT_ZIPF_ALPHA:-1.0}"
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE:-0.3}"
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE:-4}"
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION:-zipf}"  # uniform/zipf
CONTROLLED_DIFF_INPUT_SAME_OUTPUT_ZIPF_ALPHA="${CONTROLLED_DIFF_INPUT_SAME_OUTPUT_ZIPF_ALPHA:-1.0}"
CONTROLLED_TOP_SAMPLING_DISTRIBUTION="${CONTROLLED_TOP_SAMPLING_DISTRIBUTION:-zipf}"  # uniform/zipf
CONTROLLED_TOP_SAMPLING_ZIPF_ALPHA="${CONTROLLED_TOP_SAMPLING_ZIPF_ALPHA:-1.0}"

DEBUG_VOCAB_SIZE="${DEBUG_VOCAB_SIZE:-256}"
DEBUG_HIDDEN_SIZE="${DEBUG_HIDDEN_SIZE:-64}"
DEBUG_INTERMEDIATE_SIZE="${DEBUG_INTERMEDIATE_SIZE:-128}"
DEBUG_NUM_HIDDEN_LAYERS="${DEBUG_NUM_HIDDEN_LAYERS:-2}"
DEBUG_NUM_ATTENTION_HEADS="${DEBUG_NUM_ATTENTION_HEADS:-4}"
DEBUG_NUM_KEY_VALUE_HEADS="${DEBUG_NUM_KEY_VALUE_HEADS:-2}"
DEBUG_HEAD_DIM="${DEBUG_HEAD_DIM:-16}"
DEBUG_MAX_POSITION_EMBEDDINGS="${DEBUG_MAX_POSITION_EMBEDDINGS:-256}"

USE_MOE="${USE_MOE:-true}"  # true/false
MOE_NUM_UNIQUE_EXPERTS="${MOE_NUM_UNIQUE_EXPERTS:-4}"
MOE_NUM_EXPERTS_PER_TOK="${MOE_NUM_EXPERTS_PER_TOK:-2}"
MOE_INTERMEDIATE_SIZE="${MOE_INTERMEDIATE_SIZE:-64}"
MOE_USE_COMMON_EXPERT="${MOE_USE_COMMON_EXPERT:-true}"  # true/false
MOE_COMMON_INTERMEDIATE_SIZE="${MOE_COMMON_INTERMEDIATE_SIZE:-64}"
MOE_ROUTER_TYPE="${MOE_ROUTER_TYPE:-linear}"  # linear/mlp
MOE_ROUTER_HIDDEN_SIZE="${MOE_ROUTER_HIDDEN_SIZE:--1}"
MOE_ROUTER_ACT="${MOE_ROUTER_ACT:-silu}"
MOE_ROUTER_INPUT="${MOE_ROUTER_INPUT:-hidden}"  # hidden/attention_output
MOE_ROUTER_INPUT_POS="${MOE_ROUTER_INPUT_POS:-hidden}"  # hidden/attention_output_residual/attention_output/layer_input/q/k/v
MOE_ROUTER_INPUT_SHAPE="${MOE_ROUTER_INPUT_SHAPE:-full}"  # full/head/spectral
MOE_EXPERT_INPUT_POS="${MOE_EXPERT_INPUT_POS:-attention_output_residual}"  # hidden/attention_output_residual/attention_output/layer_input/q/k/v
MOE_EXPERT_INPUT_SHAPE="${MOE_EXPERT_INPUT_SHAPE:-full}"  # full/head/spectral
MOE_HEAD_LEVEL="${MOE_HEAD_LEVEL:-false}"  # true/false
MOE_SPECTRAL_BAND_DIMS="${MOE_SPECTRAL_BAND_DIMS:-}"  # e.g. 16,64,128
MOE_SPECTRAL_NUM_EXPERTS_PER_BAND="${MOE_SPECTRAL_NUM_EXPERTS_PER_BAND:-}"  # e.g. 0,4,4 where 0=common
MOE_SPECTRAL_TOPK_PER_BAND="${MOE_SPECTRAL_TOPK_PER_BAND:-}"  # e.g. 1,1,1
MOE_SPECTRAL_INTERMEDIATE_SIZES="${MOE_SPECTRAL_INTERMEDIATE_SIZES:-}"  # e.g. 32,48,48
MOE_SPECTRAL_UPDATE_INTERVAL="${MOE_SPECTRAL_UPDATE_INTERVAL:-100}"
MOE_SPECTRAL_WARMUP_STEPS="${MOE_SPECTRAL_WARMUP_STEPS:-100}"
MOE_SPECTRAL_SAMPLE_SIZE="${MOE_SPECTRAL_SAMPLE_SIZE:-4096}"
MOE_SPECTRAL_BASIS_MOMENTUM="${MOE_SPECTRAL_BASIS_MOMENTUM:-0.0}"
MOE_SPECTRAL_INCLUDE_TOP_IN_ROUTER="${MOE_SPECTRAL_INCLUDE_TOP_IN_ROUTER:-true}"  # true/false
USE_PRE_ROUTER="${USE_PRE_ROUTER:-false}"  # true/false
PRE_ROUTER_INPUT="${PRE_ROUTER_INPUT:-layer_input}"  # layer_input/q/k/v
PRE_ROUTER_CONTROLS_ATTENTION="${PRE_ROUTER_CONTROLS_ATTENTION:-false}"  # true/false
ATTENTION_ROUTER_LOSS_TYPE="${ATTENTION_ROUTER_LOSS_TYPE:-kl}"  # kl/pairwise/topk_logits
ATTENTION_ROUTER_LOSS_WEIGHT="${ATTENTION_ROUTER_LOSS_WEIGHT:-0.0}"
ATTENTION_ROUTER_RHO="${ATTENTION_ROUTER_RHO:-0.75}"
ROUTER_ENTROPY_FLOOR_LOSS_WEIGHT="${ROUTER_ENTROPY_FLOOR_LOSS_WEIGHT:-0.0}"
ROUTER_ENTROPY_FLOOR_ALPHA="${ROUTER_ENTROPY_FLOOR_ALPHA:-0.5}"
MOE_LOAD_BALANCE_LOSS_WEIGHT="${MOE_LOAD_BALANCE_LOSS_WEIGHT:-0.0}"
MOE_ROUTER_INHIBITION_LOSS_WEIGHT="${MOE_ROUTER_INHIBITION_LOSS_WEIGHT:-0.0}"
MOE_ROUTER_INHIBITION_TEMPERATURE="${MOE_ROUTER_INHIBITION_TEMPERATURE:-1.0}"
GROUND_TRUTH_ROUTING_MODE="${GROUND_TRUTH_ROUTING_MODE:-dispatch}"  # dispatch/supervise
MOE_ROUTER_SUPERVISION_LOSS_WEIGHT="${MOE_ROUTER_SUPERVISION_LOSS_WEIGHT:-0.0}"
MOE_ROUTER_SUPERVISION_DETACH_INPUT="${MOE_ROUTER_SUPERVISION_DETACH_INPUT:-false}"  # true/false
GROUND_TRUTH_ROUTING_STRATEGY="${GROUND_TRUTH_ROUTING_STRATEGY:-none}"  # none/hash/frequency_balanced
GROUND_TRUTH_ROUTING_FEATURE_LAYER="${GROUND_TRUTH_ROUTING_FEATURE_LAYER:-0}"  # 0=local slot, 1=higher-level unit
GROUND_TRUTH_FREQUENCY_ESTIMATE_SAMPLES="${GROUND_TRUTH_FREQUENCY_ESTIMATE_SAMPLES:-4096}"

ATTENTION_STRIDE_PATTERN="${ATTENTION_STRIDE_PATTERN-1,4}"
RESIDUAL_SOURCE_PATTERN="${RESIDUAL_SOURCE_PATTERN--1,-1}"


# ========== 动态构建 CKPT_DIR ==========
CKPT_DIR="${CKPT_DIR:-../checkpoints/single-thread-debug}"

# ========== 构建 Python 命令 ==========
ARGS=""
ARGS+=" --local_batch_size $LOCAL_BATCH_SIZE"
ARGS+=" --global_batch_size $GLOBAL_BATCH_SIZE"
ARGS+=" --save_interval $SAVE_INTERVAL"
ARGS+=" --seq_len $SEQ_LEN"
ARGS+=" --num_workers $NUM_WORKERS"
ARGS+=" --config_dir $CONFIG_DIR"
ARGS+=" --data_dir $DATA_DIR"
ARGS+=" --dataset_type $DATASET_TYPE"
ARGS+=" --ckpt_dir $CKPT_DIR"  # ← 关键：传入构建好的路径
ARGS+=" --synthetic_num_samples $SYNTHETIC_NUM_SAMPLES"
ARGS+=" --synthetic_block_size $SYNTHETIC_BLOCK_SIZE"
ARGS+=" --synthetic_num_hierarchy_layers $SYNTHETIC_NUM_HIERARCHY_LAYERS"
ARGS+=" --synthetic_content_token_count $SYNTHETIC_CONTENT_TOKEN_COUNT"
ARGS+=" --synthetic_num_units_per_layer $SYNTHETIC_NUM_UNITS_PER_LAYER"
ARGS+=" --synthetic_seed $SYNTHETIC_SEED"
ARGS+=" --synthetic_pad_token_id $SYNTHETIC_PAD_TOKEN_ID"
ARGS+=" --synthetic_min_token_id $SYNTHETIC_MIN_TOKEN_ID"
ARGS+=" --synthetic_sampling_distribution $SYNTHETIC_SAMPLING_DISTRIBUTION"
ARGS+=" --synthetic_zipf_alpha $SYNTHETIC_ZIPF_ALPHA"
if [ "$SYNTHETIC_ZIPF_SHUFFLE_RANKS" = "true" ]; then
  ARGS+=" --synthetic_zipf_shuffle_ranks"
else
  ARGS+=" --synthetic_no_zipf_shuffle_ranks"
fi
ARGS+=" --controlled_same_input_diff_output_rate $CONTROLLED_SAME_INPUT_DIFF_OUTPUT_RATE"
ARGS+=" --controlled_same_input_diff_output_size $CONTROLLED_SAME_INPUT_DIFF_OUTPUT_SIZE"
ARGS+=" --controlled_same_input_diff_output_distribution $CONTROLLED_SAME_INPUT_DIFF_OUTPUT_DISTRIBUTION"
ARGS+=" --controlled_same_input_diff_output_zipf_alpha $CONTROLLED_SAME_INPUT_DIFF_OUTPUT_ZIPF_ALPHA"
ARGS+=" --controlled_diff_input_same_output_rate $CONTROLLED_DIFF_INPUT_SAME_OUTPUT_RATE"
ARGS+=" --controlled_diff_input_same_output_size $CONTROLLED_DIFF_INPUT_SAME_OUTPUT_SIZE"
ARGS+=" --controlled_diff_input_same_output_distribution $CONTROLLED_DIFF_INPUT_SAME_OUTPUT_DISTRIBUTION"
ARGS+=" --controlled_diff_input_same_output_zipf_alpha $CONTROLLED_DIFF_INPUT_SAME_OUTPUT_ZIPF_ALPHA"
ARGS+=" --controlled_top_sampling_distribution $CONTROLLED_TOP_SAMPLING_DISTRIBUTION"
ARGS+=" --controlled_top_sampling_zipf_alpha $CONTROLLED_TOP_SAMPLING_ZIPF_ALPHA"
ARGS+=" --debug_vocab_size $DEBUG_VOCAB_SIZE"
ARGS+=" --debug_hidden_size $DEBUG_HIDDEN_SIZE"
ARGS+=" --debug_intermediate_size $DEBUG_INTERMEDIATE_SIZE"
ARGS+=" --debug_num_hidden_layers $DEBUG_NUM_HIDDEN_LAYERS"
ARGS+=" --debug_num_attention_heads $DEBUG_NUM_ATTENTION_HEADS"
ARGS+=" --debug_num_key_value_heads $DEBUG_NUM_KEY_VALUE_HEADS"
ARGS+=" --debug_head_dim $DEBUG_HEAD_DIM"
ARGS+=" --debug_max_position_embeddings $DEBUG_MAX_POSITION_EMBEDDINGS"
if [ "$USE_MOE" = "true" ]; then
  ARGS+=" --use_moe"
fi
ARGS+=" --moe_num_unique_experts $MOE_NUM_UNIQUE_EXPERTS"
ARGS+=" --moe_num_experts_per_tok $MOE_NUM_EXPERTS_PER_TOK"
ARGS+=" --moe_intermediate_size $MOE_INTERMEDIATE_SIZE"
if [ "$MOE_USE_COMMON_EXPERT" = "true" ]; then
  ARGS+=" --moe_use_common_expert"
fi
ARGS+=" --moe_common_intermediate_size $MOE_COMMON_INTERMEDIATE_SIZE"
ARGS+=" --moe_router_type $MOE_ROUTER_TYPE"
ARGS+=" --moe_router_hidden_size $MOE_ROUTER_HIDDEN_SIZE"
ARGS+=" --moe_router_act $MOE_ROUTER_ACT"
ARGS+=" --moe_router_input $MOE_ROUTER_INPUT"
ARGS+=" --moe_router_input_pos $MOE_ROUTER_INPUT_POS"
ARGS+=" --moe_router_input_shape $MOE_ROUTER_INPUT_SHAPE"
ARGS+=" --moe_expert_input_pos $MOE_EXPERT_INPUT_POS"
ARGS+=" --moe_expert_input_shape $MOE_EXPERT_INPUT_SHAPE"
if [ "$MOE_HEAD_LEVEL" = "true" ]; then
  ARGS+=" --moe_head_level"
fi
if [ -n "$MOE_SPECTRAL_BAND_DIMS" ]; then
  ARGS+=" --moe_spectral_band_dims=${MOE_SPECTRAL_BAND_DIMS}"
fi
if [ -n "$MOE_SPECTRAL_NUM_EXPERTS_PER_BAND" ]; then
  ARGS+=" --moe_spectral_num_experts_per_band=${MOE_SPECTRAL_NUM_EXPERTS_PER_BAND}"
fi
if [ -n "$MOE_SPECTRAL_TOPK_PER_BAND" ]; then
  ARGS+=" --moe_spectral_topk_per_band=${MOE_SPECTRAL_TOPK_PER_BAND}"
fi
if [ -n "$MOE_SPECTRAL_INTERMEDIATE_SIZES" ]; then
  ARGS+=" --moe_spectral_intermediate_sizes=${MOE_SPECTRAL_INTERMEDIATE_SIZES}"
fi
ARGS+=" --moe_spectral_update_interval $MOE_SPECTRAL_UPDATE_INTERVAL"
ARGS+=" --moe_spectral_warmup_steps $MOE_SPECTRAL_WARMUP_STEPS"
ARGS+=" --moe_spectral_sample_size $MOE_SPECTRAL_SAMPLE_SIZE"
ARGS+=" --moe_spectral_basis_momentum $MOE_SPECTRAL_BASIS_MOMENTUM"
if [ "$MOE_SPECTRAL_INCLUDE_TOP_IN_ROUTER" != "true" ]; then
  ARGS+=" --moe_spectral_no_include_top_in_router"
fi
if [ "$USE_PRE_ROUTER" = "true" ]; then
  ARGS+=" --use_pre_router"
fi
ARGS+=" --pre_router_input $PRE_ROUTER_INPUT"
if [ "$PRE_ROUTER_CONTROLS_ATTENTION" = "true" ]; then
  ARGS+=" --pre_router_controls_attention"
fi
ARGS+=" --attention_router_loss_type $ATTENTION_ROUTER_LOSS_TYPE"
ARGS+=" --attention_router_loss_weight $ATTENTION_ROUTER_LOSS_WEIGHT"
ARGS+=" --attention_router_rho $ATTENTION_ROUTER_RHO"
ARGS+=" --router_entropy_floor_loss_weight $ROUTER_ENTROPY_FLOOR_LOSS_WEIGHT"
ARGS+=" --router_entropy_floor_alpha $ROUTER_ENTROPY_FLOOR_ALPHA"
ARGS+=" --moe_load_balance_loss_weight $MOE_LOAD_BALANCE_LOSS_WEIGHT"
ARGS+=" --moe_router_inhibition_loss_weight $MOE_ROUTER_INHIBITION_LOSS_WEIGHT"
ARGS+=" --moe_router_inhibition_temperature $MOE_ROUTER_INHIBITION_TEMPERATURE"
ARGS+=" --ground_truth_routing_mode $GROUND_TRUTH_ROUTING_MODE"
ARGS+=" --moe_router_supervision_loss_weight $MOE_ROUTER_SUPERVISION_LOSS_WEIGHT"
if [ "$MOE_ROUTER_SUPERVISION_DETACH_INPUT" = "true" ]; then
  ARGS+=" --moe_router_supervision_detach_input"
fi
ARGS+=" --ground_truth_routing_strategy $GROUND_TRUTH_ROUTING_STRATEGY"
ARGS+=" --ground_truth_routing_feature_layer $GROUND_TRUTH_ROUTING_FEATURE_LAYER"
ARGS+=" --ground_truth_frequency_estimate_samples $GROUND_TRUTH_FREQUENCY_ESTIMATE_SAMPLES"
ARGS+=" --attention_stride_pattern=${ATTENTION_STRIDE_PATTERN}"
ARGS+=" --residual_source_pattern=${RESIDUAL_SOURCE_PATTERN}"


# 处理布尔参数
if [ "$DATA_SHUFFLE" = "true" ]; then
  ARGS+=" --data_shuffle"
else
  ARGS+=" --no_data_shuffle"
fi

if [ "$USE_BF16" = "true" ]; then
  ARGS+=" --use_bf16"
else
  ARGS+=" --no_use_bf16"
fi

ARGS+=" --optimizer $OPTIMIZER"
ARGS+=" --lr $LR"
ARGS+=" --warmup_steps $WARMUP_STEPS"
ARGS+=" --total_training_steps $TOTAL_TRAINING_STEPS"
ARGS+=" --training_seed $TRAINING_SEED"

python3 single_thread_debug.py ${ARGS}
