#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/home/fdong/qksieve_iclr2027}"
RUN_ROOT="${RUN_ROOT:-${ROOT}/results/qksieve_optimized_profile_20260807}"
GPU="${GPU:-0}"
HISTORY_TOKENS="${HISTORY_TOKENS:-32768}"
EVAL_TOKENS="${EVAL_TOKENS:-64}"
TEXT_FILE="${TEXT_FILE:-${ROOT}/src/run_head_top2_targeted_ppl_pre_indexopt_20260807.py}"

if [[ ! -f "${TEXT_FILE}" ]]; then
  echo "Frozen speed corpus does not exist: ${TEXT_FILE}" >&2
  exit 1
fi

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-2}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-2}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-2}"
export QKSIEVE_QK_FACTOR_SOLVER=legacy
export QKSIEVE_QMSE_RATE_ALLOCATOR=torch
export QKSIEVE_PRELOAD_EXTENSIONS=1
export QKSIEVE_PRELOAD_QMSE_RATE_TABLES=1
export QKSIEVE_BUILD_RESIDENT_VALUE_SKETCH=1
export QKSIEVE_RESIDENT_VALUE_WORKERS="${QKSIEVE_RESIDENT_VALUE_WORKERS:-12}"
export QKSIEVE_PARALLEL_QK_WORKERS="${QKSIEVE_PARALLEL_QK_WORKERS:-36}"
export QKSIEVE_PARALLEL_VALUE_WORKERS=0
export QKSIEVE_FUSED_WOMETRIC_VALUE_APPEND=1
export QKSIEVE_BATCH_QMSE_ALLOCATION=1
export QKSIEVE_RESIDENT_VALUE_ATTENTION_WORKSPACE="${QKSIEVE_RESIDENT_VALUE_ATTENTION_WORKSPACE:-1}"
export QKSIEVE_TILED_VALUE_ATTENTION="${QKSIEVE_TILED_VALUE_ATTENTION:-0}"
export QKSIEVE_VALUE_SKETCH_TAIL_ALPHA=1.0
unset QKSIEVE_PROFILE_STAGES || true
unset QKSIEVE_EXACT_SELECTION_DIAGNOSTICS || true
unset QKSIEVE_BUILD_RESIDENT_KEY_FACTORS || true
unset QKSIEVE_RESIDENT_KEY_MOMENTS_ONLY || true

GPU="${GPU}" \
HISTORY_TOKENS="${HISTORY_TOKENS}" \
EVAL_TOKENS="${EVAL_TOKENS}" \
TEXT_FILE="${TEXT_FILE}" \
RUN_ROOT="${RUN_ROOT}" \
SOLVERS=legacy \
bash "${ROOT}/scripts/launch_qksieve_index_profile_20260807.sh"
